SchedulingSystemWeb/Pages/Admin/Roles/Upsert.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CheaperByTheDozen.Pages.Roles
{
    public class UpsertModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public UpsertModel(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public IdentityRole CurrentRole { get; set; }
        [BindProperty]
        public bool IsUpdate { get; set; }

        public async Task OnGetAsync(string? id)
        {
            if (id != null)
            {
                CurrentRole = await _roleManager.FindByIdAsync(id);
                IsUpdate = true;
            }
            else
            {
                CurrentRole = new IdentityRole();
                IsUpdate = false;
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if (!IsUpdate)
            {
                CurrentRole.NormalizedName = CurrentRole.Name.ToUpper();

                await _roleManager.CreateAsync(CurrentRole);
                return RedirectToPage("./Index", new { success = true, message = "Successfully Added" });
            }
            else
            {
                CurrentRole.NormalizedName = CurrentRole.Name.ToUpper();

                await _roleManager.UpdateAsync(CurrentRole);
                return RedirectToPage("./Index", new { success = true, message = "Update Successful" });
            }

        }
    }
}

SchedulingSystemWeb/Pages/Student/Bookings/Upsert.cshtml.cs
using DataAccess;
using Infrastructure.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Infrastructure.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
//using Microsoft.Identity.Client;
using static System.Formats.Asn1.AsnWriter;
using System.Globalization;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;
using Microsoft.Graph;
using Microsoft.Extensions.Http;
using System.Collections.Generic;
using System.Threading.Tasks;

using ClientCredential = Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential;
using static Google.Apis.Calendar.v3.CalendarService;
using System.Net.Http.Headers;
using Microsoft.Graph.Models;
using Azure.Identity;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Identity.Client;
using SendGrid.Helpers.Mail;
using SendGrid;
using Microsoft.AspNetCore.Authorization;
using System;
namespace SchedulingSystemWeb.Pages.Student.Bookings
{
    [Authorize(Roles = "STUDENT, TUTOR")]
    public class UpsertModel : PageModel
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        public Availability availability = new Availability();
        public string startEndTime;
        public string fullName { get; set; }
        public Infrastructure.Models.Location location { get; set; }
        [BindProperty(SupportsGet = true)]
        public string course { get; set; }
        public Booking newBooking = new Booking();
        [BindProperty(SupportsGet = true)]
        public string title { get; set; }
        public static int? AId;
        [BindProperty(SupportsGet = true)]
        public string description { get; set; }
        public ApplicationUser user { get; set; }
        public List<string> ProvRole { get; set; }
        public ProviderProfile prov { get; set; }
        private IWebHostEnvironment _webhostenvironment;
        public IEnumerable<Category> AvCategories { get; set; }
        [BindProperty]
        public List<int> CategoryIds { get; set; } = new List<int>();
        public UpsertModel(UnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, IWebHostEnvironment webhostenvironment, IHttpClientFactory httpClientFactory)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _webhostenvironment = webhostenvironment;
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> OnGetAsync(int? Id)
        {
            AId = Id;
            
            availability = _unitOfWork.Availability.Get(a => a.Id == Id);
            startEndTime = availability.StartTime.TimeOfDay + "-" + availability.EndTime.TimeOfDay;
            prov = _unitOfWork.ProviderProfile.Get(u => u.Id == availability.ProviderProfileID);
            user = _unitOfWork.ApplicationUser.Get(u => u.Id == prov.User);
            ProvRole = (List<string>) await _userManager.GetRolesAsync(user);
            fullName = user.FirstName + " " + user.LastName;
            var locationID = availability.LocationId;
            location = _unitOfWork.Location.Get(l => l.LocationId == locationID);
            AvCategories = _unitOfWork.Category.GetAll().Where(c => availability.Category.Contains(c.Id));
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            TimeZoneInfo localTimeZone = TimeZoneInfo.Local;
            availability = _unitOfWork.Availability.Get(a => a.Id == AId);
            newBooking.StartTime = availability.StartTime;
            newBooking.Duration = (int)(availability.EndTime - availability.StartTime).TotalMinutes;
            newBooking.Subject = course;
            newBooking.ProviderProfileID = availability.ProviderProfileID;
            newBooking.CategoryID = int.Parse(Request.Form["CategoryIds"]);
            //newBooking.User = await _userManager.GetUserAsync(User);
            newBooking.Note = description;
            //newBooking.MeetingTitle = title;
            newBooking.User = _userManager.GetUserId(User);
            newBooking.objAvailability = availability.Id;
            string webRootPath = _webhostenvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            newBooking.Attachment = new List<String>();
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    
                    // Create unique identifier
                    string fileName = Guid.NewGuid().ToString();
                    // Get and preserve extension type
                    var extension = Path.GetExtension(file.FileName);
                    // Create path to /images/products folder
                    var uploads = Path.Combine(webRootPath, @"bookingFiles\");
                    // Create full path
                    var fullPath = Path.Combine(uploads, fileName + extension);
                    // Stream the binary files to the server
                    using var fileStream = System.IO.File.Create(fullPath);
                    file.CopyTo(fileStream);
                    // Associate real URL and save to DB
                    newBooking.Attachment.Add(@"\bookingFiles\" + fileName + extension);
                    
                }
            }
            if (course == null)
            {
                newBooking.Subject = "";
            }
            _unitOfWork.Booking.Add(newBooking); //Reactivate when ready.
            _unitOfWork.Commit();
            await SendEmail(newBooking);
           
            
            if (User.IsInRole("STUDENT"))
            {
                return Redirect("/student/home/index");
            }
            else if (User.IsInRole("TUTOR"))
            {
                return Redirect("/tutor/home/index");
            }

            return Redirect("/Index");
        }
        public async Task SendEmail(Booking newBooking)
        {   
            ProviderProfile p = _unitOfWork.ProviderProfile.Get(p => p.Id == newBooking.ProviderProfileID);
            ApplicationUser Teacherinfo = _unitOfWork.ApplicationUser.Get(u => u.Id == p.User);
            ApplicationUser student = _unitOfWork.ApplicationUser.Get(b => b.Id == newBooking.User);

            var sendgridclient = new SendGridClient("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");
            var from = new SendGrid.Helpers.Mail.EmailAddress("CodemonkeysScheduling@outlook.com", "Code Monkeys");
            var to = new SendGrid.Helpers.Mail.EmailAddress(Teacherinfo.Email, Teacherinfo.FirstName + " " + Teacherinfo.LastName);
            var subject = "Booking Created";
            var plainText = student.FirstName + " " + student.LastName + " Created an appointment on " + newBooking.StartTime.ToShortDateString() + " at " + newBooking.StartTime.ToShortTimeString();
            var htmlContent = "<p>" + plainText + "</p>";
            var message = MailHelper.CreateSingleEmail(from, to, subject, plainText, htmlContent);
            var response = await sendgridclient.SendEmailAsync(message); //Teacher Message
            to = new SendGrid.Helpers.Mail.EmailAddress(student.Email, student.FirstName + " " + student.LastName);
            plainText = "You successfully made a booking with " + Teacherinfo.FirstName + " " + Teacherinfo.LastName + " on " + newBooking.StartTime.ToShortDateString() + " at " + newBooking.StartTime.ToShortTimeString();
            htmlContent = "<p>" + plainText + "</p>";
            message = MailHelper.CreateSingleEmail(from, to, subject, plainText, htmlContent);
            response = await sendgridclient.SendEmailAsync(message); //Student Message
        }
    }
}

SchedulingSystemWeb/Pages/Teacher/Appointments/Index.cshtml.cs
using DataAccess;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Calendar.v3;
using Google.Apis.Services;
using Google.Apis.Util.Store;
using Infrastructure.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Util.Store;

namespace SchedulingSystemWeb.Pages.Teacher.Appointments
{
    [Authorize(Roles = "TUTOR, TEACHER, ADVISOR")]
    public class IndexModel : PageModel
    {
        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public IndexModel(UnitOfWork unitOfWork, UserManager<ApplicationUser> userman, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _userManager = userman;
            _webHostEnvironment = webHostEnvironment;

        }
        //Public Variables
        public Booking booking { get; set; }
        public ApplicationUser student { get; set; }
        public ApplicationUser teacher { get; set; }
        public List<string> filepath { get; set; }
        public Location location { get; set; }
        public Availability aval { get; set; }
        public CustomerProfile studprofile { get; set; }
        public bool isTutor { get; set; }
        public async Task OnGet(int? id)
        {


            int provId = _unitOfWork.ProviderProfile.Get(p => p.User == _userManager.GetUserId(User)).Id;
            booking = _unitOfWork.Booking.Get(b => b.Id == id & b.ProviderProfileID == provId);
            teacher = _unitOfWork.ApplicationUser.Get(u => u.Id == _userManager.GetUserId(User));
            student = _unitOfWork.ApplicationUser.Get(s => s.Id == booking.User);
            aval = _unitOfWork.Availability.Get(i => i.Id == booking.objAvailability);
            location = _unitOfWork.Location.Get(l => l.LocationId == aval.LocationId);
            if (await _userManager.IsInRoleAsync(student, "TUTOR"))
            {
                isTutor = true;
                // User is in the "TUTOR" role
            }
            else
            {
                studprofile = _unitOfWork.CustomerProfile.Get(d => d.User == student.Id);
            }
            
            filepath = new List<string>();
            if (booking.Attachment != null && booking.Attachment.Count() > 0)
            {
                string wwwroot = _webHostEnvironment.WebRootPath;
                foreach (var attachmentPath in booking.Attachment)
                {
                    // Parse the attachmentPath to remove the square brackets and quotes
                    string[] parts = attachmentPath.ToString().Trim(new char[] { '[', ']', '"' }).Split(',');

                    // Trim each part to remove leading and trailing whitespace
                    for (int i = 0; i < parts.Length; i++)
                    {
                        parts[i] = parts[i].Trim();
                    }

                    // Combine the parts to get the file path
                    filepath.Add(Path.Combine(wwwroot, parts[0]));

                    // Use filePath as needed
                }
            }

        }
       
    }
}

SchedulingSystemWeb/Pages/Teacher/Availabilities/Delete.cshtml.cs
using DataAccess;
using Infrastructure.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchedulingSystemWeb.Pages.Teacher.Availabilities
{
    [Authorize(Roles = "TUTOR, TEACHER, ADVISOR")]
    public class DeleteModel : PageModel
    {
        private readonly UnitOfWork _unitOfWork;
        public DeleteModel(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public Availability availability { get; set; }
        public void OnGet(int? id)
        {
            availability = _unitOfWork.Availability.Get(i=> i.Id == id);
        }
        public async Task<IActionResult> OnPost(int? id ) 
        {
            availability = _unitOfWork.Availability.Get(i => i.Id == id);
            _unitOfWork.Availability.Delete(availability);
            _unitOfWork.Commit();
            return Redirect("/Teacher/Availabilities");
        }
    }
}

SchedulingSystemWeb/Pages/Teacher/Locations/Index.cshtml.cs
using DataAccess;
using Infrastructure.Interfaces;
using Infrastructure.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Shared;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SchedulingSystemWeb.Pages.Teacher.Locations
{
    [Authorize(Roles = "TUTOR, TEACHER, ADVISOR, ADMIN")]
    public class IndexModel : PageModel
    {

        private readonly UnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        public IEnumerable<Location> LocationList { get; set; }
        public ProviderProfile providerProfile { get; set; }
        [BindProperty]
        [Display(Name = "Remote Link")]
        public string RemoteLink { get; set; }
        public IEnumerable<LocationType> locationTypes { get; set; }
        public List<(Location, string campusName)> locationCompoundList { get; set; }

        [BindProperty]
        public bool Edit { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public IndexModel(UnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            locationCompoundList = new List<(Location, string)>();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Edit = false;
            await LoadData();
            return Page();
        }

        public async Task OnPostEdit()
        {
            Edit = true;
            await LoadData();
        }

        private async Task LoadData()
        {
            providerProfile = _unitOfWork.ProviderProfile.Get(p => p.User == _userManager.GetUserId(User));
            LocationList = _unitOfWork.Location.GetAll().Where(l => l.ProfileId == providerProfile.Id);
            locationCompoundList.Clear();
            foreach (var loc in LocationList)
            {
                var locationTypeName = _unitOfWork.LocationType.Get(l => l.Id == loc.LocationType).LocationTypeName;
                locationCompoundList.Add((loc, locationTypeName));
            }
            RemoteLink = providerProfile.RemoteLink;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var existingProfile = _unitOfWork.ProviderProfile.Get(p => p.User == _userManager.GetUserId(User));
            if (existingProfile != null)
            {
                existingProfile.RemoteLink = RemoteLink;
                _unitOfWork.ProviderProfile.Update(existingProfile);
                await _unitOfWork.CommitAsync();
                StatusMessage = "Virtual Meeting Link Updated";
            }

            Edit = false; 
            await LoadData();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var location = _unitOfWork.Location.Get(l => l.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            _unitOfWork.Location.Delete(location);
            await _unitOfWork.CommitAsync();
            return RedirectToPage();
        }

    }
}

SchedulingSystemWeb/Pages/Teacher/Locations/Index.cshtml
@page
@model SchedulingSystemWeb.Pages.Teacher.Locations.IndexModel
@{
    ViewData["Title"] = "Locations";
}

<h2 class="text-primary">@ViewData["Title"]</h2>
@* <partial name="_StatusMessage" for="StatusMessage" /> *@

<div class="row">
    <div class="col-md-6">
        @{
            if (!Model.Edit)
            {
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-title">Virtual Meeting Link</p>
                            <hr />
                            <p class="card-text">
                                <input asp-for="RemoteLink" disabled="disabled" class="form-control" />
                            </p>
                            <form method="post">
                                <button type="submit" asp-page-handler="Edit" class="btn btn-primary">Edit</button>
                            </form>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <form method="post">
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <p class="card-title">Virtual</p>
                                <hr />
                                <p class="card-text">
                                    <input asp-for="RemoteLink" class="form-control" />
                                </p>
                                <button id="update-remoteLink-button" asp-page-handler="" type="submit" class="w-100 btn btn-lg btn-primary">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            }
        }
        
        
        <br />
        <br />
        <h4>
            Appointment Locations
        </h4>
        <a asp-page="/Teacher/Locations/Upsert" class="btn btn-success">Create a new Location</a>
        @foreach (var (location, campusName) in Model.locationCompoundList)
        {
            <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <p class="card-title">@location.LocationName</p>
                    <hr />
                    <p class="card-text">@location.BuildingName</p>
                    <p class="card-text">@location.RoomNumber</p>
                    <p class="card-text">Campus: @campusName</p>
                    <a asp-page="/Teacher/Locations/Upsert" asp-route-id="@location.LocationId" class="btn btn-primary">Edit</a>
                    <form method="post" asp-page-handler="Delete" onsubmit="return confirm('Are you sure you want to delete this location?');">
                        <input type="hidden" asp-for="@location.LocationId" name="id" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
            </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    <script>

    </script>
}

SchedulingSystemWeb/Pages/Teacher/Locations/Upsert.cshtml
@page
@model SchedulingSystemWeb.Pages.Teacher.Locations.UpsertModel
@{
}

<h2>@(Model.objLocation.LocationId == 0 ? "Create New Location" : "Edit Location")</h2>

<form method="post">
    <input type="hidden" asp-for="objLocation.LocationId" />

    <div class="mb-3">
        <label for="Name" class="form-label">Name: </label>
        <input type="text" class="form-control" id="Name" asp-for="objLocation.LocationName" required>
    </div>

    <div class="mb-3">
        <label for="BuildingName" class="form-label">Building: </label>
        <input type="text" class="form-control" id="BuildingName" asp-for="objLocation.BuildingName">
    </div>

    <div class="mb-3">
        <label for="RoomNum" class="form-label">Room Number: </label>
        <input type="text" class="form-control" id="RoomNum" asp-for="objLocation.RoomNumber">
    </div>

    <div class="mb-3">
        <label for="LocationType" class="form-label">Campus:</label>
        <select asp-for="objLocation.LocationType" class="form-control" required>
            <option value="">-- Select Campus --</option>
            @foreach (var type in Model.typeList)
            {
                <option value="@type.Id">@type.LocationTypeName</option>
            }
        </select>
    </div>
    


    <button type="submit" class="btn btn-primary">Submit</button>
</form>